# Collection {#collect}

Data collection is the process of collecting data. 
Before construction of a data collection protocol, 
the reader should be familiar with future aspects of the data management 
pipeline and thus I suggest reading (or at least skimming) through the remainder
of the book in order to fully understand the suggests given here. 

There are three main methods of data collection

  1. manual entry,
  1. digital entry, and
  1. automated digital process.
  
In manual entry the data are written down on paper and 
will need to be entered into a computer and saved as a digital file later. 
In direct digital entry, 
an individual inputs the data directly into a 
computer and saves the results as a digital file, 
but does not have an original paper copy.
Finally, an automated digital file is created by a machine connected to 
a computer and the machine automatically creates a digital file.

  
## Manual entry

In field and laboratory settings, 
data are often recorded using pen on paper. 
Eventually these data will be recorded on in a digital, and therefore usable,
format, but, as collected, the data are distinctly unusable. 



### Construction of lab notebook or field sheets

To make the lab notebook and field sheet amenable to digitization,
contruction of these 



## Digital entry



## Automated digital process

